#!/bin/bash

# shellcheck disable=SC1090
. "$(dirname "$0")/alltags.sh"

IMG=$(basename "$DOCKER_REPO")
for tag in $(alltags "$IMG"); do
    echo "======================= Pushing ${DOCKER_REPO}:$tag"
    docker push "${DOCKER_REPO}:$tag"
done