#!/usr/bin/env sh

# shellcheck disable=SC1091
. "$(dirname "$0")/reg-tags/image_tags.sh"

MINVER=${MINVER:-3.6}

for tag in $(img_tags --filter '[0-9]+(\.[0-9]+)+$' --verbose -- "$(basename "$DOCKER_REPO")"); do
    if [ "$(img_version "$tag")" -ge "$(img_version "$MINVER")" ]; then
        if docker image inspect "${DOCKER_REPO}:$tag" >/dev/null 2>&1; then
            echo "============== Pushing ${DOCKER_REPO}:$tag"
            docker push "${DOCKER_REPO}:$tag"
        else
            echo "!!!!!!!!!!!!!! ${DOCKER_REPO}:$tag was not built, cannot push!"
        fi
    fi
done
