name: alpine

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
      - cron: "0 0 * * *"

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build GHCR images
        env:
          DOCKER_REPO: ghcr.io/yanzinetworks/alpine
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
      -
        name: Push GHCR images
        env:
          DOCKER_REPO: ghcr.io/yanzinetworks/alpine
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push
      -
        name: Login to Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Docker Hub images
        env:
          DOCKER_REPO: docker.io/yanzinetworks/alpine
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/build
      -
        name: Push Docker Hub images
        env:
          DOCKER_REPO: docker.io/yanzinetworks/alpine
          SOURCE_COMMIT: ${{ github.sha }}
        run: ./hooks/push
